FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /workspace

COPY pom.xml ./
COPY src ./src

EXPOSE 8080 5005

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]
